FROM nginx:alpine

# Copy static HTML as a placeholder app
COPY index.html /usr/share/nginx/html/index.html

# Optionally copy custom nginx config
# COPY ../nginx/nginx.conf /etc/nginx/conf.d/default.conf
